using CVControl.Data.Entidades;

namespace CVControl.Data.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<DataContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(DataContext ctx)
        {
            ctx.IntervaloIdades.AddOrUpdate(x => x.IdIntervaloIdade,
                new IntervaloIdade { IdIntervaloIdade = 1, Intervalo = "Menor de 10 anos" },
                new IntervaloIdade { IdIntervaloIdade = 2, Intervalo = "Entre 10 e 25 anos" },
                new IntervaloIdade { IdIntervaloIdade = 3, Intervalo = "Entre 25 e 35 anos" },
                new IntervaloIdade { IdIntervaloIdade = 4, Intervalo = "Entre 35 e 50 anos" },
                new IntervaloIdade { IdIntervaloIdade = 5, Intervalo = "Mais de 50" }
                );

            ctx.Generos.AddOrUpdate(X => X.IdGenero,
                new Genero { IdGenero = 1, Nome = "Feminino" },
                new Genero { IdGenero = 2, Nome = "Masculino" }
                );

            ctx.IntervalosFilhos.AddOrUpdate(x=>x.IdIntervaloFilhos,
                new IntervaloFilhos{IdIntervaloFilhos = 1, Intervalo = "Nenhum"},
                new IntervaloFilhos{IdIntervaloFilhos = 2, Intervalo = "1 o 2 filhos"},
                new IntervaloFilhos{IdIntervaloFilhos = 3, Intervalo = "3 a 5 filhos"},
                new IntervaloFilhos{IdIntervaloFilhos = 4, Intervalo = "Mais de 5"}
                );

            ctx.EstadosCivis.AddOrUpdate(x => x.IdEstadoCivil,
                new EstadoCivil { IdEstadoCivil = 1, Estado = "Solteiro(a)" },
                new EstadoCivil { IdEstadoCivil = 2, Estado = "Casado(a)" },
                new EstadoCivil { IdEstadoCivil = 3, Estado = "Divorciado(a)" },
                new EstadoCivil { IdEstadoCivil = 4, Estado = "Viuvo(a)" }
                );

            ctx.Sintomas.AddOrUpdate(x => x.IdSintomas,
                new Sintoma { IdSintomas = 1, Nome = "Coriza" },
                new Sintoma { IdSintomas = 2, Nome = "Nariz entupido" },
                new Sintoma { IdSintomas = 3, Nome = "Espirros" },
                new Sintoma { IdSintomas = 4, Nome = "Tosse" },
                new Sintoma { IdSintomas = 5, Nome = "Dor de cabeça" },
                new Sintoma { IdSintomas = 6, Nome = "Dores no corpo" },
                new Sintoma { IdSintomas = 7, Nome = "Mal estar geral" },
                new Sintoma { IdSintomas = 8, Nome = "Dor de garganta" }
                );

            ctx.Provincias.AddOrUpdate(x => x.IdProvincia,
                new Provincia { IdProvincia = 1, Nome = "Bengo" },
                new Provincia { IdProvincia = 2, Nome = "Benguela" },
                new Provincia { IdProvincia = 3, Nome = "Bié" },
                new Provincia { IdProvincia = 4, Nome = "Cabinda" },
                new Provincia { IdProvincia = 5, Nome = "Cunene" },
                new Provincia { IdProvincia = 6, Nome = "Huambo" },
                new Provincia { IdProvincia = 7, Nome = "Huíla" },
                new Provincia { IdProvincia = 8, Nome = "Kuando Kubango" },
                new Provincia { IdProvincia = 9, Nome = "Kwanza Norte" },
                new Provincia { IdProvincia = 10, Nome = "Kwanza Sul" },
                new Provincia { IdProvincia = 11, Nome = "Luanda" },
                new Provincia { IdProvincia = 12, Nome = "Lunda Norte" },
                new Provincia { IdProvincia = 13, Nome = "Lunda Sul" },
                new Provincia { IdProvincia = 14, Nome = "Malange" },
                new Provincia { IdProvincia = 15, Nome = "Moxico" },
                new Provincia { IdProvincia = 16, Nome = "Namibe" },
                new Provincia { IdProvincia = 17, Nome = "Uíge" },
                new Provincia { IdProvincia = 18, Nome = "Zaire" }
                );

            ctx.Municipios.AddOrUpdate(x => x.IdMunicipio,
                new Municipio { IdMunicipio = 1, IdProvincia = 1, Nome = "Ambriz" },
                new Municipio { IdMunicipio = 2, IdProvincia = 1, Nome = "Dande" },
                new Municipio { IdMunicipio = 3, IdProvincia = 1, Nome = "Dembos" },
                new Municipio { IdMunicipio = 4, IdProvincia = 1, Nome = "Bula Atumba" },
                new Municipio { IdMunicipio = 5, IdProvincia = 1, Nome = "Nambuangongo" },
                new Municipio { IdMunicipio = 6, IdProvincia = 1, Nome = "Pango Aluquém (Pango Aluquêm)" },
                new Municipio { IdMunicipio = 7, IdProvincia = 2, Nome = "Balombo" },
                new Municipio { IdMunicipio = 8, IdProvincia = 2, Nome = "Baía Farta" },
                new Municipio { IdMunicipio = 9, IdProvincia = 2, Nome = "Benguela" },
                new Municipio { IdMunicipio = 10, IdProvincia = 2, Nome = "Bocoio" },
                new Municipio { IdMunicipio = 11, IdProvincia = 2, Nome = "Caimbambo" },
                new Municipio { IdMunicipio = 12, IdProvincia = 2, Nome = "Catumbela" },
                new Municipio { IdMunicipio = 13, IdProvincia = 2, Nome = "Chongoroi" },
                new Municipio { IdMunicipio = 14, IdProvincia = 2, Nome = "Cubal" },
                new Municipio { IdMunicipio = 15, IdProvincia = 2, Nome = "Ganda" },
                new Municipio { IdMunicipio = 16, IdProvincia = 2, Nome = "Lobito" },
                new Municipio { IdMunicipio = 17, IdProvincia = 3, Nome = "Andulo" },
                new Municipio { IdMunicipio = 18, IdProvincia = 3, Nome = "Camacupa" },
                new Municipio { IdMunicipio = 19, IdProvincia = 3, Nome = "Catabola" },
                new Municipio { IdMunicipio = 20, IdProvincia = 3, Nome = "Chinguar" },
                new Municipio { IdMunicipio = 21, IdProvincia = 3, Nome = "Chitembo" },
                new Municipio { IdMunicipio = 22, IdProvincia = 3, Nome = "Cuemba" },
                new Municipio { IdMunicipio = 23, IdProvincia = 3, Nome = "Cunhinga" },
                new Municipio { IdMunicipio = 24, IdProvincia = 3, Nome = "Cuito (Kuito)" },
                new Municipio { IdMunicipio = 25, IdProvincia = 3, Nome = "Nharêa" },
                new Municipio { IdMunicipio = 26, IdProvincia = 4, Nome = "Belize" },
                new Municipio { IdMunicipio = 27, IdProvincia = 4, Nome = "Buco-Zau" },
                new Municipio { IdMunicipio = 28, IdProvincia = 4, Nome = "Cabinda" },
                new Municipio { IdMunicipio = 29, IdProvincia = 4, Nome = "Cacongo" },
                new Municipio { IdMunicipio = 30, IdProvincia = 5, Nome = "Cahama" },
                new Municipio { IdMunicipio = 31, IdProvincia = 5, Nome = "Cuanhama (Kwanhama)" },
                new Municipio { IdMunicipio = 32, IdProvincia = 5, Nome = "Curoca" },
                new Municipio { IdMunicipio = 33, IdProvincia = 5, Nome = "Cuvelai" },
                new Municipio { IdMunicipio = 34, IdProvincia = 5, Nome = "Namacunde" },
                new Municipio { IdMunicipio = 35, IdProvincia = 5, Nome = "Ombadja" },
                new Municipio { IdMunicipio = 36, IdProvincia = 6, Nome = "Bailundo" },
                new Municipio { IdMunicipio = 37, IdProvincia = 6, Nome = "Cachiungo (Catchiungo)" },
                new Municipio { IdMunicipio = 38, IdProvincia = 6, Nome = "Caála" },
                new Municipio { IdMunicipio = 39, IdProvincia = 6, Nome = "Ecunha (Ekunha)" },
                new Municipio { IdMunicipio = 40, IdProvincia = 6, Nome = "Huambo" },
                new Municipio { IdMunicipio = 41, IdProvincia = 6, Nome = "Londuimbali" },
                new Municipio { IdMunicipio = 42, IdProvincia = 6, Nome = "Longonjo (Longongo)" },
                new Municipio { IdMunicipio = 43, IdProvincia = 6, Nome = "Mungo" },
                new Municipio { IdMunicipio = 44, IdProvincia = 6, Nome = "Chicala-Cholohanga (Tchicala-Tcholoanga)" },
                new Municipio { IdMunicipio = 45, IdProvincia = 6, Nome = "Chinjenje (Tchindjenje)" },
                new Municipio { IdMunicipio = 46, IdProvincia = 6, Nome = "Ucuma" },
                new Municipio { IdMunicipio = 47, IdProvincia = 7, Nome = "Caconda" },
                new Municipio { IdMunicipio = 48, IdProvincia = 7, Nome = "Cacula" },
                new Municipio { IdMunicipio = 49, IdProvincia = 7, Nome = "Caluquembe" },
                new Municipio { IdMunicipio = 50, IdProvincia = 7, Nome = "Gambos" },
                new Municipio { IdMunicipio = 51, IdProvincia = 7, Nome = "Chibia" },
                new Municipio { IdMunicipio = 52, IdProvincia = 7, Nome = "Chicomba" },
                new Municipio { IdMunicipio = 53, IdProvincia = 7, Nome = "Chipindo" },
                new Municipio { IdMunicipio = 54, IdProvincia = 7, Nome = "Humpata" },
                new Municipio { IdMunicipio = 55, IdProvincia = 7, Nome = "Jamba" },
                new Municipio { IdMunicipio = 56, IdProvincia = 7, Nome = "Cuvango (Kuvango)" },
                new Municipio { IdMunicipio = 57, IdProvincia = 7, Nome = "Lubango" },
                new Municipio { IdMunicipio = 58, IdProvincia = 7, Nome = "Matala" },
                new Municipio { IdMunicipio = 59, IdProvincia = 7, Nome = "Quilengues" },
                new Municipio { IdMunicipio = 60, IdProvincia = 7, Nome = "Quipungo" },
                new Municipio { IdMunicipio = 61, IdProvincia = 8, Nome = "Calai" },
                new Municipio { IdMunicipio = 62, IdProvincia = 8, Nome = "Cuangar" },
                new Municipio { IdMunicipio = 63, IdProvincia = 8, Nome = "Cuchi" },
                new Municipio { IdMunicipio = 64, IdProvincia = 8, Nome = "Cuito Cuanavale (Kuito Kuanavale)" },
                new Municipio { IdMunicipio = 65, IdProvincia = 8, Nome = "Dirico" },
                new Municipio { IdMunicipio = 66, IdProvincia = 8, Nome = "Nancova (Nankova)" },
                new Municipio { IdMunicipio = 67, IdProvincia = 8, Nome = "Mavinga" },
                new Municipio { IdMunicipio = 68, IdProvincia = 8, Nome = "Menongue" },
                new Municipio { IdMunicipio = 69, IdProvincia = 8, Nome = "Rivungo" },
                new Municipio { IdMunicipio = 70, IdProvincia = 9, Nome = "Ambaca" },
                new Municipio { IdMunicipio = 71, IdProvincia = 9, Nome = "Banga" },
                new Municipio { IdMunicipio = 72, IdProvincia = 9, Nome = "Bolongongo" },
                new Municipio { IdMunicipio = 73, IdProvincia = 9, Nome = "Cambambe" },
                new Municipio { IdMunicipio = 74, IdProvincia = 9, Nome = "Cazengo" },
                new Municipio { IdMunicipio = 75, IdProvincia = 9, Nome = "Golungo Alto" },
                new Municipio { IdMunicipio = 76, IdProvincia = 9, Nome = "Ngonguembo (Gonguembo)" },
                new Municipio { IdMunicipio = 77, IdProvincia = 9, Nome = "Lucala" },
                new Municipio { IdMunicipio = 78, IdProvincia = 9, Nome = "Quiculungo" },
                new Municipio { IdMunicipio = 79, IdProvincia = 9, Nome = "Samba Caju" },
                new Municipio { IdMunicipio = 80, IdProvincia = 10, Nome = "Amboim" },
                new Municipio { IdMunicipio = 81, IdProvincia = 10, Nome = "Cassongue" },
                new Municipio { IdMunicipio = 82, IdProvincia = 10, Nome = "Conda" },
                new Municipio { IdMunicipio = 83, IdProvincia = 10, Nome = "Ebo" },
                new Municipio { IdMunicipio = 84, IdProvincia = 10, Nome = "Libolo" },
                new Municipio { IdMunicipio = 85, IdProvincia = 10, Nome = "Mussende" },
                new Municipio { IdMunicipio = 86, IdProvincia = 10, Nome = "Porto Amboim" },
                new Municipio { IdMunicipio = 87, IdProvincia = 10, Nome = "Quibala" },
                new Municipio { IdMunicipio = 88, IdProvincia = 10, Nome = "Quilenda" },
                new Municipio { IdMunicipio = 89, IdProvincia = 10, Nome = "Seles" },
                new Municipio { IdMunicipio = 90, IdProvincia = 10, Nome = "Sumbe" },
                new Municipio { IdMunicipio = 91, IdProvincia = 10, Nome = "Cela" },
                new Municipio { IdMunicipio = 92, IdProvincia = 11, Nome = "Belas" },
                new Municipio { IdMunicipio = 93, IdProvincia = 11, Nome = "Cacuaco" },
                new Municipio { IdMunicipio = 94, IdProvincia = 11, Nome = "Cazenga" },
                new Municipio { IdMunicipio = 95, IdProvincia = 11, Nome = "Icolo e Bengo" },
                new Municipio { IdMunicipio = 96, IdProvincia = 11, Nome = "Luanda" },
                new Municipio { IdMunicipio = 97, IdProvincia = 11, Nome = "Quiçama (Quissama)" },
                new Municipio { IdMunicipio = 98, IdProvincia = 11, Nome = "Kilamba Kiaxi" },
                new Municipio { IdMunicipio = 99, IdProvincia = 11, Nome = "Talatona" },
                new Municipio { IdMunicipio = 100, IdProvincia = 11, Nome = "Viana" },
                new Municipio { IdMunicipio = 101, IdProvincia = 12, Nome = "Cambulo" },
                new Municipio { IdMunicipio = 102, IdProvincia = 12, Nome = "Capenda Camulemba" },
                new Municipio { IdMunicipio = 103, IdProvincia = 12, Nome = "Caungula" },
                new Municipio { IdMunicipio = 104, IdProvincia = 12, Nome = "Chitato (Tchitato)" },
                new Municipio { IdMunicipio = 105, IdProvincia = 12, Nome = "Cuango" },
                new Municipio { IdMunicipio = 106, IdProvincia = 12, Nome = "Cuilo" },
                new Municipio { IdMunicipio = 107, IdProvincia = 12, Nome = "Lubalo" },
                new Municipio { IdMunicipio = 108, IdProvincia = 12, Nome = "Lucapa" },
                new Municipio { IdMunicipio = 109, IdProvincia = 12, Nome = "Xá Muteba" },
                new Municipio { IdMunicipio = 110, IdProvincia = 12, Nome = "Lóvua" },
                new Municipio { IdMunicipio = 111, IdProvincia = 13, Nome = "Cacolo" },
                new Municipio { IdMunicipio = 112, IdProvincia = 13, Nome = "Dala" },
                new Municipio { IdMunicipio = 113, IdProvincia = 13, Nome = "Muconda" },
                new Municipio { IdMunicipio = 114, IdProvincia = 13, Nome = "Saurimo" },
                new Municipio { IdMunicipio = 115, IdProvincia = 14, Nome = "Cacuso" },
                new Municipio { IdMunicipio = 116, IdProvincia = 14, Nome = "Calandula" },
                new Municipio { IdMunicipio = 117, IdProvincia = 14, Nome = "Cambundi Catembo" },
                new Municipio { IdMunicipio = 118, IdProvincia = 14, Nome = "Cangandala" },
                new Municipio { IdMunicipio = 119, IdProvincia = 14, Nome = "Cahombo (Caombo)" },
                new Municipio { IdMunicipio = 120, IdProvincia = 14, Nome = "Kiwaba Nzoji (Cuaba Nzogo)" },
                new Municipio { IdMunicipio = 121, IdProvincia = 14, Nome = "Kunda dya Baze (Cunda-Diaza)" },
                new Municipio { IdMunicipio = 122, IdProvincia = 14, Nome = "Luquembo" },
                new Municipio { IdMunicipio = 123, IdProvincia = 14, Nome = "Malange" },
                new Municipio { IdMunicipio = 124, IdProvincia = 14, Nome = "Marimba" },
                new Municipio { IdMunicipio = 125, IdProvincia = 14, Nome = "Massango" },
                new Municipio { IdMunicipio = 126, IdProvincia = 14, Nome = "Mucari" },
                new Municipio { IdMunicipio = 127, IdProvincia = 14, Nome = "Quela" },
                new Municipio { IdMunicipio = 128, IdProvincia = 14, Nome = "Quirima" },
                new Municipio { IdMunicipio = 129, IdProvincia = 15, Nome = "Alto Zambeze" },
                new Municipio { IdMunicipio = 130, IdProvincia = 15, Nome = "Bundas" },
                new Municipio { IdMunicipio = 131, IdProvincia = 15, Nome = "Camanongue" },
                new Municipio { IdMunicipio = 132, IdProvincia = 15, Nome = "Cameia (Lumeji)" },
                new Municipio { IdMunicipio = 133, IdProvincia = 15, Nome = "Luau" },
                new Municipio { IdMunicipio = 134, IdProvincia = 15, Nome = "Luacano (Lucano)" },
                new Municipio { IdMunicipio = 135, IdProvincia = 15, Nome = "Luchazes" },
                new Municipio { IdMunicipio = 136, IdProvincia = 15, Nome = "Léua" },
                new Municipio { IdMunicipio = 137, IdProvincia = 15, Nome = "Moxico" },
                new Municipio { IdMunicipio = 138, IdProvincia = 16, Nome = "Bibala" },
                new Municipio { IdMunicipio = 139, IdProvincia = 16, Nome = "Camacuio (Camulo)" },
                new Municipio { IdMunicipio = 140, IdProvincia = 16, Nome = "Moçâmedes (Namibe)" },
                new Municipio { IdMunicipio = 141, IdProvincia = 16, Nome = "Tômbwa (Tômbua)" },
                new Municipio { IdMunicipio = 142, IdProvincia = 16, Nome = "Virei" },
                new Municipio { IdMunicipio = 143, IdProvincia = 17, Nome = "Alto Cauale" },
                new Municipio { IdMunicipio = 144, IdProvincia = 17, Nome = "Ambuíla" },
                new Municipio { IdMunicipio = 145, IdProvincia = 17, Nome = "Bembe" },
                new Municipio { IdMunicipio = 146, IdProvincia = 17, Nome = "Buengas" },
                new Municipio { IdMunicipio = 147, IdProvincia = 17, Nome = "Bungo" },
                new Municipio { IdMunicipio = 148, IdProvincia = 17, Nome = "Damba" },
                new Municipio { IdMunicipio = 149, IdProvincia = 17, Nome = "Milunga" },
                new Municipio { IdMunicipio = 150, IdProvincia = 17, Nome = "Mucaba" },
                new Municipio { IdMunicipio = 151, IdProvincia = 17, Nome = "Negage" },
                new Municipio { IdMunicipio = 152, IdProvincia = 17, Nome = "Puri" },
                new Municipio { IdMunicipio = 153, IdProvincia = 17, Nome = "Quimbele" },
                new Municipio { IdMunicipio = 154, IdProvincia = 17, Nome = "Dange-Quitexe" },
                new Municipio { IdMunicipio = 155, IdProvincia = 17, Nome = "Pombo" },
                new Municipio { IdMunicipio = 156, IdProvincia = 17, Nome = "Songo" },
                new Municipio { IdMunicipio = 157, IdProvincia = 17, Nome = "Uíge" },
                new Municipio { IdMunicipio = 158, IdProvincia = 17, Nome = "Maquela do Zombo" },
                new Municipio { IdMunicipio = 159, IdProvincia = 18, Nome = "Cuimba" },
                new Municipio { IdMunicipio = 160, IdProvincia = 18, Nome = "M'Banza Kongo" },
                new Municipio { IdMunicipio = 161, IdProvincia = 18, Nome = "Noqui" },
                new Municipio { IdMunicipio = 162, IdProvincia = 18, Nome = "N'Zeto" },
                new Municipio { IdMunicipio = 163, IdProvincia = 18, Nome = "Soyo" },
                new Municipio { IdMunicipio = 164, IdProvincia = 18, Nome = "Tomboco" }
                );

            ctx.SaveChanges();
        }
    }
}
